// import './vendor/vendor.js';
// import './moduls/iframe.js';
// import './moduls/tabs-price.js';
// import './moduls/swiper.js';
// import './moduls/tabs-faq.js';
import './vendor/vendor.js';
import './moduls/iframe.js';
import './moduls/tabs-price.js';
import './moduls/tabs-faq.js';
import './moduls/swiper.js';
import './moduls/form.js';
